services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\FontDownloader\:
    resource: '../Classes/*'

  WapplerSystems\FontDownloader\FontLoader\FontLoaderRegistry:
    public: true
    arguments:
      - !tagged_iterator fontloader